#!/bin/sh

HERE="$(dirname "$(readlink -f "${0}")")"
export LD_LIBRARY_PATH="${HERE}"/libs
#export QT_PLUGIN_PATH="${HERE}"/libs/qt5/plugins 
#export QT_QPA_PLATFORM_PLUGIN_PATH="${HERE}"/libs/qt5/plugins/platforms
exec "${HERE}"/pifu-hello $@
